# Generated by Django 3.2 on 2021-04-14 15:01

import django.db.models.deletion
from django.db import migrations, models

import cadastro.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "dt_cadastro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
                (
                    "dt_modificacao",
                    models.DateField(auto_now=True, verbose_name="Último atualização"),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Somente números",
                        max_length=11,
                        unique=True,
                        validators=[cadastro.utils.validate_cpf],
                        verbose_name="CPF do Contratante",
                    ),
                ),
                ("nome", models.CharField(max_length=35, verbose_name="Nome")),
                (
                    "sobrenome",
                    models.CharField(max_length=35, verbose_name="Sobrenome"),
                ),
                ("contato_1", models.CharField(max_length=11, verbose_name="Celular")),
                ("contato_2", models.CharField(max_length=11, verbose_name="Telefone")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("rua", models.CharField(max_length=50, verbose_name="Endereço")),
                ("num_casa", models.CharField(max_length=6, verbose_name="Número")),
                ("bairro", models.CharField(max_length=50, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
            ],
            options={
                "verbose_name": "Cadastro de Cliente",
                "verbose_name_plural": "Cadastro de Clientes",
            },
        ),
        migrations.CreateModel(
            name="Sistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "sistema",
                    models.CharField(
                        help_text="Informe o nome do sistema",
                        max_length=30,
                        unique=True,
                        verbose_name="Sistema",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do sistema")),
                (
                    "dt_cadastro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
                (
                    "dt_modidicacao",
                    models.DateField(auto_now=True, verbose_name="Último atualização"),
                ),
            ],
            options={
                "verbose_name": "Cadastro de Sistema",
                "verbose_name_plural": "Cadastro de Sistemas",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "dt_cadastro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
                (
                    "dt_modificacao",
                    models.DateField(auto_now=True, verbose_name="Último atualização"),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Somente números",
                        max_length=14,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=50, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=50, verbose_name="Nome Fantasia"),
                ),
                ("rua", models.CharField(max_length=50, verbose_name="Endereço")),
                ("num_casa", models.CharField(max_length=6, verbose_name="Número")),
                ("bairro", models.CharField(max_length=50, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                (
                    "contratante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_empresa",
                        to="cadastro.cliente",
                        verbose_name="Contratante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro de Empresa",
                "verbose_name_plural": "Cadastro de Empresas",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("dt_inicio", models.DateField(verbose_name="Início do Contrato")),
                ("dt_fim", models.DateField(verbose_name="Encerramento do Contrato")),
                (
                    "mensalidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Parcela mensal (R$)",
                    ),
                ),
                (
                    "anuidade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Valor total do contrato (R$)",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.CharField(
                        choices=[
                            ("05", "Dia 5"),
                            ("10", "Dia 10"),
                            ("15", "Dia 15"),
                            ("20", "Dia 20"),
                            ("25", "Dia 25"),
                        ],
                        max_length=2,
                        verbose_name="Dia de vencimento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "contratante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresa_contrato",
                        to="cadastro.empresa",
                        verbose_name="Contratante",
                    ),
                ),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.sistema",
                        verbose_name="Sistema Contratado",
                    ),
                ),
            ],
        ),
    ]
