# Generated by Django 3.2 on 2021-04-15 12:02

import uuid

from django.db import migrations, models

import cadastro.utils


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_auto_20210414_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="contrato_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to=cadastro.utils.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="nm_contrato",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                help_text="Somente números",
                max_length=11,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="dia_vencimento",
            field=models.CharField(
                choices=[
                    ("10", "Dia 10"),
                    ("15", "Dia 15"),
                    ("20", "Dia 20"),
                    ("25", "Dia 25"),
                    ("28", "Dia 28"),
                ],
                max_length=2,
                verbose_name="Dia de vencimento",
            ),
        ),
    ]
