# Generated by Django 3.2 on 2021-04-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_auto_20210415_0902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="anuidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Valor Total"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="dt_fim",
            field=models.DateField(verbose_name="Final"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="dt_inicio",
            field=models.DateField(verbose_name="Início"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="nm_contrato",
            field=models.CharField(max_length=30, verbose_name="Contrato"),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.sistema",
                verbose_name="Sistema",
            ),
        ),
    ]
