# Generated by Django 3.2 on 2021-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0005_auto_20210415_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="nm_contrato",
            field=models.CharField(max_length=60, verbose_name="Contrato"),
        ),
    ]
