# Generated by Django 3.2 on 2021-06-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20210614_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_contrato', to='cadastro.sistema', verbose_name='Sistema'),
        ),
    ]
