# Generated by Django 3.2 on 2021-07-21 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0008_alter_contrato_sistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="sefaz",
            field=models.CharField(
                help_text="Somente números",
                max_length=14,
                null=True,
                unique=True,
                verbose_name="SEFAZ",
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="observacoes",
            field=models.TextField(
                default="Sem observações", null=True, verbose_name="Observações"
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="sistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sistema_contrato",
                to="cadastro.sistema",
                verbose_name="Sistema",
            ),
        ),
    ]
